# Generated by Django 3.1.6 on 2021-03-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210304_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.subcategory'),
        ),
    ]
