# Generated by Django 3.1.6 on 2021-03-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210304_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(default=None, upload_to='main_images'),
            preserve_default=False,
        ),
    ]
