# Generated by Django 3.1.6 on 2021-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210311_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uz_heading',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
