# Generated by Django 3.1.6 on 2021-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210312_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uz_heading',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
