# Generated by Django 3.1.6 on 2021-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210312_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='oz_subheading',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='uz_subheading',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
