# Generated by Django 3.1.6 on 2021-03-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210312_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblock',
            old_name='content',
            new_name='ru_content',
        ),
    ]
