# Generated by Django 3.1.6 on 2021-03-12 12:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210312_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='oz_content',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentblock',
            name='uz_content',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
    ]
